In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/Iceland_energy_data.csv")

In [ ]:
df

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,ISL,Iceland,1965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,NaN,NaN,0.000,NaN,0.000,0.000,0.000
1,ISL,Iceland,1966,NaN,NaN,NaN,NaN,NaN,NaN,4.981,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
2,ISL,Iceland,1967,NaN,NaN,NaN,NaN,NaN,NaN,-1.018,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
3,ISL,Iceland,1968,NaN,NaN,NaN,NaN,NaN,NaN,5.811,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
4,ISL,Iceland,1969,NaN,NaN,NaN,NaN,NaN,NaN,-0.529,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
5,ISL,Iceland,1970,NaN,NaN,NaN,NaN,NaN,NaN,20.593,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
6,ISL,Iceland,1971,NaN,NaN,NaN,NaN,NaN,NaN,8.841,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
7,ISL,Iceland,1972,NaN,NaN,NaN,NaN,NaN,NaN,8.709,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
8,ISL,Iceland,1973,NaN,NaN,NaN,NaN,NaN,NaN,20.728,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
9,ISL,Iceland,1974,NaN,NaN,NaN,NaN,NaN,NaN,-2.612,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
10,ISL,Iceland,1975,NaN,NaN,NaN,NaN,NaN,NaN,-4.102,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
11,ISL,Iceland,1976,NaN,NaN,NaN,NaN,NaN,NaN,3.305,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
12,ISL,Iceland,1977,NaN,NaN,NaN,NaN,NaN,NaN,5.783,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
13,ISL,Iceland,1978,NaN,NaN,NaN,NaN,NaN,NaN,4.426,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
14,ISL,Iceland,1979,NaN,NaN,NaN,NaN,NaN,NaN,4.188,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
15,ISL,Iceland,1980,NaN,NaN,NaN,NaN,NaN,NaN,1.204,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
16,ISL,Iceland,1981,NaN,0.0,NaN,0.0,NaN,0.0,1.955,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
17,ISL,Iceland,1982,NaN,0.0,NaN,0.0,NaN,0.0,2.372,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
18,ISL,Iceland,1983,NaN,0.0,NaN,0.0,NaN,0.0,3.198,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
19,ISL,Iceland,1984,NaN,0.0,NaN,0.0,NaN,0.0,5.253,...,0.0,0.0,0.0,NaN,NaN,0.000,0.000,0.000,0.000,0.000
20,ISL,Iceland,1985,NaN,0.0,NaN,0.0,NaN,0.0,-1.017,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
21,ISL,Iceland,1986,NaN,0.0,NaN,0.0,NaN,0.0,4.536,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
22,ISL,Iceland,1987,NaN,0.0,NaN,0.0,NaN,0.0,3.196,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
23,ISL,Iceland,1988,NaN,0.0,NaN,0.0,NaN,0.0,5.459,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
24,ISL,Iceland,1989,NaN,0.0,NaN,0.0,NaN,0.0,3.576,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
25,ISL,Iceland,1990,NaN,0.0,NaN,0.0,NaN,0.0,0.091,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
26,ISL,Iceland,1991,NaN,0.0,NaN,0.0,NaN,0.0,-2.387,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
27,ISL,Iceland,1992,NaN,0.0,NaN,0.0,NaN,0.0,3.533,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
28,ISL,Iceland,1993,NaN,0.0,NaN,0.0,NaN,0.0,3.885,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
29,ISL,Iceland,1994,NaN,0.0,NaN,0.0,NaN,0.0,1.118,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
30,ISL,Iceland,1995,NaN,0.0,NaN,0.0,NaN,0.0,3.197,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
31,ISL,Iceland,1996,NaN,0.0,NaN,0.0,NaN,0.0,5.964,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
32,ISL,Iceland,1997,NaN,0.0,NaN,0.0,NaN,0.0,4.754,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
33,ISL,Iceland,1998,NaN,0.0,NaN,0.0,NaN,0.0,8.157,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
34,ISL,Iceland,1999,NaN,0.0,NaN,0.0,NaN,0.0,9.537,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
35,ISL,Iceland,2000,NaN,0.0,NaN,0.0,NaN,0.0,6.178,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
36,ISL,Iceland,2001,NaN,0.0,NaN,0.0,NaN,0.0,1.034,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
37,ISL,Iceland,2002,NaN,0.0,NaN,0.0,NaN,0.0,3.866,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
38,ISL,Iceland,2003,NaN,0.0,NaN,0.0,NaN,0.0,0.492,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
39,ISL,Iceland,2004,NaN,0.0,NaN,0.0,NaN,0.0,2.040,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
40,ISL,Iceland,2005,NaN,0.0,NaN,0.0,NaN,0.0,0.409,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
41,ISL,Iceland,2006,NaN,0.0,NaN,0.0,NaN,0.0,9.783,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
42,ISL,Iceland,2007,NaN,0.0,NaN,0.0,NaN,0.0,14.230,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
43,ISL,Iceland,2008,NaN,0.0,NaN,0.0,NaN,0.0,24.732,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
44,ISL,Iceland,2009,NaN,0.0,NaN,0.0,NaN,0.0,-0.157,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
45,ISL,Iceland,2010,NaN,0.0,NaN,0.0,NaN,0.0,-0.004,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
46,ISL,Iceland,2011,NaN,0.0,NaN,0.0,NaN,0.0,0.013,...,0.0,0.0,0.0,0.000,NaN,0.000,0.000,0.000,0.000,0.064
47,ISL,Iceland,2012,NaN,0.0,NaN,0.0,NaN,0.0,0.990,...,0.0,0.0,0.0,0.000,-100.000,0.000,-0.000,0.000,0.000,0.000
48,ISL,Iceland,2013,NaN,0.0,NaN,0.0,NaN,0.0,3.194,...,0.0,0.0,0.0,0.000,NaN,0.025,0.014,0.014,0.000,42.958
49,ISL,Iceland,2014,NaN,0.0,NaN,0.0,NaN,0.0,-0.132,...,0.0,0.0,0.0,0.055,51.779,0.038,0.007,0.021,30.433,64.924
50,ISL,Iceland,2015,NaN,0.0,NaN,0.0,NaN,0.0,4.368,...,0.0,0.0,0.0,0.053,29.167,0.047,0.006,0.028,30.281,83.442
51,ISL,Iceland,2016,NaN,0.0,NaN,0.0,NaN,0.0,0.505,...,0.0,0.0,0.0,0.054,-15.927,0.039,-0.004,0.023,30.102,69.735
52,ISL,Iceland,2017,NaN,NaN,NaN,NaN,NaN,NaN,4.608,...,0.0,0.0,0.0,0.052,-12.350,0.033,-0.003,0.020,29.905,60.723
53,ISL,Iceland,2018,NaN,NaN,NaN,NaN,NaN,NaN,3.603,...,0.0,0.0,0.0,0.000,-46.648,0.017,-0.009,0.011,0.000,32.174
54,ISL,Iceland,2019,NaN,NaN,NaN,NaN,NaN,NaN,-4.796,...,0.0,0.0,0.0,0.051,50.256,0.027,0.005,0.016,29.495,48.012
55,ISL,Iceland,2020,NaN,NaN,NaN,NaN,NaN,NaN,-6.256,...,0.0,0.0,0.0,0.052,1.024,0.029,0.000,0.016,29.304,48.189

In [ ]:
df = df.fillna('')

In [ ]:
df

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,ISL,Iceland,1965,,,,,,,,...,0.0,0.0,0.0,,,0.000,,0.000,0.000,0.000
1,ISL,Iceland,1966,,,,,,,4.981,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
2,ISL,Iceland,1967,,,,,,,-1.018,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
3,ISL,Iceland,1968,,,,,,,5.811,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
4,ISL,Iceland,1969,,,,,,,-0.529,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
5,ISL,Iceland,1970,,,,,,,20.593,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
6,ISL,Iceland,1971,,,,,,,8.841,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
7,ISL,Iceland,1972,,,,,,,8.709,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
8,ISL,Iceland,1973,,,,,,,20.728,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
9,ISL,Iceland,1974,,,,,,,-2.612,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
10,ISL,Iceland,1975,,,,,,,-4.102,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
11,ISL,Iceland,1976,,,,,,,3.305,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
12,ISL,Iceland,1977,,,,,,,5.783,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
13,ISL,Iceland,1978,,,,,,,4.426,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
14,ISL,Iceland,1979,,,,,,,4.188,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
15,ISL,Iceland,1980,,,,,,,1.204,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
16,ISL,Iceland,1981,,0.0,,0.0,,0.0,1.955,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
17,ISL,Iceland,1982,,0.0,,0.0,,0.0,2.372,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
18,ISL,Iceland,1983,,0.0,,0.0,,0.0,3.198,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
19,ISL,Iceland,1984,,0.0,,0.0,,0.0,5.253,...,0.0,0.0,0.0,,,0.000,0.0,0.000,0.000,0.000
20,ISL,Iceland,1985,,0.0,,0.0,,0.0,-1.017,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
21,ISL,Iceland,1986,,0.0,,0.0,,0.0,4.536,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
22,ISL,Iceland,1987,,0.0,,0.0,,0.0,3.196,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
23,ISL,Iceland,1988,,0.0,,0.0,,0.0,5.459,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
24,ISL,Iceland,1989,,0.0,,0.0,,0.0,3.576,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
25,ISL,Iceland,1990,,0.0,,0.0,,0.0,0.091,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
26,ISL,Iceland,1991,,0.0,,0.0,,0.0,-2.387,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
27,ISL,Iceland,1992,,0.0,,0.0,,0.0,3.533,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
28,ISL,Iceland,1993,,0.0,,0.0,,0.0,3.885,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
29,ISL,Iceland,1994,,0.0,,0.0,,0.0,1.118,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
30,ISL,Iceland,1995,,0.0,,0.0,,0.0,3.197,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
31,ISL,Iceland,1996,,0.0,,0.0,,0.0,5.964,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
32,ISL,Iceland,1997,,0.0,,0.0,,0.0,4.754,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
33,ISL,Iceland,1998,,0.0,,0.0,,0.0,8.157,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
34,ISL,Iceland,1999,,0.0,,0.0,,0.0,9.537,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
35,ISL,Iceland,2000,,0.0,,0.0,,0.0,6.178,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
36,ISL,Iceland,2001,,0.0,,0.0,,0.0,1.034,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
37,ISL,Iceland,2002,,0.0,,0.0,,0.0,3.866,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
38,ISL,Iceland,2003,,0.0,,0.0,,0.0,0.492,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
39,ISL,Iceland,2004,,0.0,,0.0,,0.0,2.04,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
40,ISL,Iceland,2005,,0.0,,0.0,,0.0,0.409,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
41,ISL,Iceland,2006,,0.0,,0.0,,0.0,9.783,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
42,ISL,Iceland,2007,,0.0,,0.0,,0.0,14.23,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
43,ISL,Iceland,2008,,0.0,,0.0,,0.0,24.732,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
44,ISL,Iceland,2009,,0.0,,0.0,,0.0,-0.157,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
45,ISL,Iceland,2010,,0.0,,0.0,,0.0,-0.004,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.000
46,ISL,Iceland,2011,,0.0,,0.0,,0.0,0.013,...,0.0,0.0,0.0,0.0,,0.000,0.0,0.000,0.000,0.064
47,ISL,Iceland,2012,,0.0,,0.0,,0.0,0.99,...,0.0,0.0,0.0,0.0,-100.0,0.000,-0.0,0.000,0.000,0.000
48,ISL,Iceland,2013,,0.0,,0.0,,0.0,3.194,...,0.0,0.0,0.0,0.0,,0.025,0.014,0.014,0.000,42.958
49,ISL,Iceland,2014,,0.0,,0.0,,0.0,-0.132,...,0.0,0.0,0.0,0.055,51.779,0.038,0.007,0.021,30.433,64.924
50,ISL,Iceland,2015,,0.0,,0.0,,0.0,4.368,...,0.0,0.0,0.0,0.053,29.167,0.047,0.006,0.028,30.281,83.442
51,ISL,Iceland,2016,,0.0,,0.0,,0.0,0.505,...,0.0,0.0,0.0,0.054,-15.927,0.039,-0.004,0.023,30.102,69.735
52,ISL,Iceland,2017,,,,,,,4.608,...,0.0,0.0,0.0,0.052,-12.35,0.033,-0.003,0.020,29.905,60.723
53,ISL,Iceland,2018,,,,,,,3.603,...,0.0,0.0,0.0,0.0,-46.648,0.017,-0.009,0.011,0.000,32.174
54,ISL,Iceland,2019,,,,,,,-4.796,...,0.0,0.0,0.0,0.051,50.256,0.027,0.005,0.016,29.495,48.012
55,ISL,Iceland,2020,,,,,,,-6.256,...,0.0,0.0,0.0,0.052,1.024,0.029,0.0,0.016,29.304,48.189

In [ ]:
num_duplicates = df.duplicated().sum()
num_duplicates

0

In [ ]:
df.isnull().sum()

iso_code                   0
country                    0
year                       0
coal_prod_change_pct      56
coal_prod_change_twh      20
                          ..
wind_share_energy          0
wind_cons_change_twh       1
wind_consumption           0
wind_elec_per_capita       0
wind_energy_per_capita     0
Length: 128, dtype: int64

In [ ]:
null_percentage = df.isnull().sum() / len(df) * 100

In [ ]:
null_percentage

iso_code                    0.000000
country                     0.000000
year                        0.000000
coal_prod_change_pct      100.000000
coal_prod_change_twh       35.714286
                             ...
wind_share_energy           0.000000
wind_cons_change_twh        1.785714
wind_consumption            0.000000
wind_elec_per_capita        0.000000
wind_energy_per_capita      0.000000
Length: 128, dtype: float64

In [ ]:
df = df.apply(pd.to_numeric, errors='coerce')

In [ ]:
print(df.dtypes)

iso_code                  float64
country                   float64
year                        int64
coal_prod_change_pct      float64
coal_prod_change_twh      float64
                           ...
wind_share_energy         float64
wind_cons_change_twh      float64
wind_consumption          float64
wind_elec_per_capita      float64
wind_energy_per_capita    float64
Length: 128, dtype: object

In [ ]:
median_values = df.median()

In [ ]:
print("Median values for each column:")
print(median_values)

Median values for each column:
iso_code                     NaN
country                      NaN
year                      1992.5
coal_prod_change_pct         NaN
coal_prod_change_twh         0.0
                           ...
wind_share_energy            0.0
wind_cons_change_twh         0.0
wind_consumption             0.0
wind_elec_per_capita         0.0
wind_energy_per_capita       0.0
Length: 128, dtype: float64

In [ ]:
df.fillna(median_values,inplace=True)

In [ ]:
df

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,NaN,NaN,1965,NaN,0.0,NaN,0.0,NaN,0.0,3.305,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
1,NaN,NaN,1966,NaN,0.0,NaN,0.0,NaN,0.0,4.981,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
2,NaN,NaN,1967,NaN,0.0,NaN,0.0,NaN,0.0,-1.018,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
3,NaN,NaN,1968,NaN,0.0,NaN,0.0,NaN,0.0,5.811,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
4,NaN,NaN,1969,NaN,0.0,NaN,0.0,NaN,0.0,-0.529,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
5,NaN,NaN,1970,NaN,0.0,NaN,0.0,NaN,0.0,20.593,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
6,NaN,NaN,1971,NaN,0.0,NaN,0.0,NaN,0.0,8.841,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
7,NaN,NaN,1972,NaN,0.0,NaN,0.0,NaN,0.0,8.709,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
8,NaN,NaN,1973,NaN,0.0,NaN,0.0,NaN,0.0,20.728,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
9,NaN,NaN,1974,NaN,0.0,NaN,0.0,NaN,0.0,-2.612,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
10,NaN,NaN,1975,NaN,0.0,NaN,0.0,NaN,0.0,-4.102,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
11,NaN,NaN,1976,NaN,0.0,NaN,0.0,NaN,0.0,3.305,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
12,NaN,NaN,1977,NaN,0.0,NaN,0.0,NaN,0.0,5.783,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
13,NaN,NaN,1978,NaN,0.0,NaN,0.0,NaN,0.0,4.426,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
14,NaN,NaN,1979,NaN,0.0,NaN,0.0,NaN,0.0,4.188,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
15,NaN,NaN,1980,NaN,0.0,NaN,0.0,NaN,0.0,1.204,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
16,NaN,NaN,1981,NaN,0.0,NaN,0.0,NaN,0.0,1.955,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
17,NaN,NaN,1982,NaN,0.0,NaN,0.0,NaN,0.0,2.372,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
18,NaN,NaN,1983,NaN,0.0,NaN,0.0,NaN,0.0,3.198,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
19,NaN,NaN,1984,NaN,0.0,NaN,0.0,NaN,0.0,5.253,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
20,NaN,NaN,1985,NaN,0.0,NaN,0.0,NaN,0.0,-1.017,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
21,NaN,NaN,1986,NaN,0.0,NaN,0.0,NaN,0.0,4.536,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
22,NaN,NaN,1987,NaN,0.0,NaN,0.0,NaN,0.0,3.196,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
23,NaN,NaN,1988,NaN,0.0,NaN,0.0,NaN,0.0,5.459,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
24,NaN,NaN,1989,NaN,0.0,NaN,0.0,NaN,0.0,3.576,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
25,NaN,NaN,1990,NaN,0.0,NaN,0.0,NaN,0.0,0.091,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
26,NaN,NaN,1991,NaN,0.0,NaN,0.0,NaN,0.0,-2.387,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
27,NaN,NaN,1992,NaN,0.0,NaN,0.0,NaN,0.0,3.533,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
28,NaN,NaN,1993,NaN,0.0,NaN,0.0,NaN,0.0,3.885,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
29,NaN,NaN,1994,NaN,0.0,NaN,0.0,NaN,0.0,1.118,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
30,NaN,NaN,1995,NaN,0.0,NaN,0.0,NaN,0.0,3.197,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
31,NaN,NaN,1996,NaN,0.0,NaN,0.0,NaN,0.0,5.964,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
32,NaN,NaN,1997,NaN,0.0,NaN,0.0,NaN,0.0,4.754,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
33,NaN,NaN,1998,NaN,0.0,NaN,0.0,NaN,0.0,8.157,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
34,NaN,NaN,1999,NaN,0.0,NaN,0.0,NaN,0.0,9.537,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
35,NaN,NaN,2000,NaN,0.0,NaN,0.0,NaN,0.0,6.178,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
36,NaN,NaN,2001,NaN,0.0,NaN,0.0,NaN,0.0,1.034,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
37,NaN,NaN,2002,NaN,0.0,NaN,0.0,NaN,0.0,3.866,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
38,NaN,NaN,2003,NaN,0.0,NaN,0.0,NaN,0.0,0.492,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
39,NaN,NaN,2004,NaN,0.0,NaN,0.0,NaN,0.0,2.040,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
40,NaN,NaN,2005,NaN,0.0,NaN,0.0,NaN,0.0,0.409,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
41,NaN,NaN,2006,NaN,0.0,NaN,0.0,NaN,0.0,9.783,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
42,NaN,NaN,2007,NaN,0.0,NaN,0.0,NaN,0.0,14.230,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
43,NaN,NaN,2008,NaN,0.0,NaN,0.0,NaN,0.0,24.732,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
44,NaN,NaN,2009,NaN,0.0,NaN,0.0,NaN,0.0,-0.157,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
45,NaN,NaN,2010,NaN,0.0,NaN,0.0,NaN,0.0,-0.004,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.000
46,NaN,NaN,2011,NaN,0.0,NaN,0.0,NaN,0.0,0.013,...,0.0,0.0,0.0,0.000,-5.663,0.000,0.000,0.000,0.000,0.064
47,NaN,NaN,2012,NaN,0.0,NaN,0.0,NaN,0.0,0.990,...,0.0,0.0,0.0,0.000,-100.000,0.000,-0.000,0.000,0.000,0.000
48,NaN,NaN,2013,NaN,0.0,NaN,0.0,NaN,0.0,3.194,...,0.0,0.0,0.0,0.000,-5.663,0.025,0.014,0.014,0.000,42.958
49,NaN,NaN,2014,NaN,0.0,NaN,0.0,NaN,0.0,-0.132,...,0.0,0.0,0.0,0.055,51.779,0.038,0.007,0.021,30.433,64.924
50,NaN,NaN,2015,NaN,0.0,NaN,0.0,NaN,0.0,4.368,...,0.0,0.0,0.0,0.053,29.167,0.047,0.006,0.028,30.281,83.442
51,NaN,NaN,2016,NaN,0.0,NaN,0.0,NaN,0.0,0.505,...,0.0,0.0,0.0,0.054,-15.927,0.039,-0.004,0.023,30.102,69.735
52,NaN,NaN,2017,NaN,0.0,NaN,0.0,NaN,0.0,4.608,...,0.0,0.0,0.0,0.052,-12.350,0.033,-0.003,0.020,29.905,60.723
53,NaN,NaN,2018,NaN,0.0,NaN,0.0,NaN,0.0,3.603,...,0.0,0.0,0.0,0.000,-46.648,0.017,-0.009,0.011,0.000,32.174
54,NaN,NaN,2019,NaN,0.0,NaN,0.0,NaN,0.0,-4.796,...,0.0,0.0,0.0,0.051,50.256,0.027,0.005,0.016,29.495,48.012
55,NaN,NaN,2020,NaN,0.0,NaN,0.0,NaN,0.0,-6.256,...,0.0,0.0,0.0,0.052,1.024,0.029,0.000,0.016,29.304,48.189

In [ ]:
excel_file_path = 'output.xlsx'

In [ ]:
df.to_excel(excel_file_path,index=False)

In [ ]:
print("Dataset copied to Excel sucessfully")

Dataset copied to Excel sucessfully

In [ ]:
def detect_outliers_iqr(column):
    Q1 = column.quantile(0.25)
    Q3 = column.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return (column < lower_bound) | (column > upper_bound)

In [ ]:
outliers = df.apply(detect_outliers_iqr)

In [ ]:
outliers_count = outliers.sum()

In [ ]:
print("Number of outliers in each column:")
print(outliers_count)

Number of outliers in each column:
iso_code                  0
country                   0
year                      0
coal_prod_change_pct      0
coal_prod_change_twh      0
                         ..
wind_share_energy         8
wind_cons_change_twh      7
wind_consumption          8
wind_elec_per_capita      6
wind_energy_per_capita    9
Length: 128, dtype: int64

In [ ]:
from scipy.stats.mstats import winsorize

In [ ]:
lower_percentile = 5
upper_percentile = 95

In [ ]:
df_win = df.apply(lambda x: winsorize(x, limits=(lower_percentile/100, upper_percentile/100)))

In [ ]:
df_win = pd.DataFrame(df_win, index=df.index, columns=df.columns)

In [ ]:
outliers_count = outliers.sum()

In [ ]:
print("Number of outliers in each column:")
print(outliers_count)

Number of outliers in each column:
iso_code                  0
country                   0
year                      0
coal_prod_change_pct      0
coal_prod_change_twh      0
                         ..
wind_share_energy         8
wind_cons_change_twh      7
wind_consumption          8
wind_elec_per_capita      6
wind_energy_per_capita    9
Length: 128, dtype: int64