In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/Indonesia_energy_data.csv")

In [ ]:
df

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,IDN,Indonesia,1900,9.3575,0.533,6.354,0.494,2.9695,1.5585,6.662,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IDN,Indonesia,1901,0.9850,0.016,6.354,0.000,78.1350,2.8260,6.662,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IDN,Indonesia,1902,-6.3410,-0.106,6.354,0.000,-39.3500,-2.5350,6.662,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IDN,Indonesia,1903,9.8960,0.155,6.354,0.000,136.9050,5.3500,6.662,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IDN,Indonesia,1904,9.4790,0.163,6.354,0.000,12.8140,1.1860,6.662,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,IDN,Indonesia,2016,-1.1630,-36.789,-1.421,-10.822,5.3880,25.4300,1.144,...,0.053,0.076,0.203,0.004,52.819,0.001,0.005,0.014,0.038,0.055
117,IDN,Indonesia,2017,1.1070,34.611,-3.163,-23.750,-4.2040,-20.9100,4.167,...,0.073,0.113,0.274,0.000,-100.000,0.000,-0.014,0.000,0.000,0.000
118,IDN,Indonesia,2018,20.9270,661.493,0.133,0.967,-3.5260,-16.7980,7.990,...,0.050,0.075,0.186,0.071,NaN,0.021,0.467,0.467,0.710,1.745
119,IDN,Indonesia,2019,10.4680,400.129,-7.168,-52.182,-3.4030,-15.6440,7.238,...,0.134,0.185,0.494,0.172,155.465,0.050,0.726,1.194,1.774,4.410
120,IDN,Indonesia,2020,-8.7040,-367.529,-6.556,-44.310,-4.6660,-20.7200,-11.782,...,1.166,0.183,4.264,0.171,-2.292,0.055,-0.027,1.166,1.718,4.264

In [ ]:
df = df.fillna('')

In [ ]:
df

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,IDN,Indonesia,1900,9.3575,0.533,6.354,0.494,2.9695,1.5585,6.662,...,,,,,,,,,,
1,IDN,Indonesia,1901,0.9850,0.016,6.354,0.000,78.1350,2.8260,6.662,...,,,,,,,,,,
2,IDN,Indonesia,1902,-6.3410,-0.106,6.354,0.000,-39.3500,-2.5350,6.662,...,,,,,,,,,,
3,IDN,Indonesia,1903,9.8960,0.155,6.354,0.000,136.9050,5.3500,6.662,...,,,,,,,,,,
4,IDN,Indonesia,1904,9.4790,0.163,6.354,0.000,12.8140,1.1860,6.662,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,IDN,Indonesia,2016,-1.1630,-36.789,-1.421,-10.822,5.3880,25.4300,1.144,...,0.053,0.076,0.203,0.004,52.819,0.001,0.005,0.014,0.038,0.055
117,IDN,Indonesia,2017,1.1070,34.611,-3.163,-23.750,-4.2040,-20.9100,4.167,...,0.073,0.113,0.274,0.0,-100.0,0.0,-0.014,0.0,0.0,0.0
118,IDN,Indonesia,2018,20.9270,661.493,0.133,0.967,-3.5260,-16.7980,7.990,...,0.05,0.075,0.186,0.071,,0.021,0.467,0.467,0.71,1.745
119,IDN,Indonesia,2019,10.4680,400.129,-7.168,-52.182,-3.4030,-15.6440,7.238,...,0.134,0.185,0.494,0.172,155.465,0.05,0.726,1.194,1.774,4.41
120,IDN,Indonesia,2020,-8.7040,-367.529,-6.556,-44.310,-4.6660,-20.7200,-11.782,...,1.166,0.183,4.264,0.171,-2.292,0.055,-0.027,1.166,1.718,4.264

In [ ]:
print(df.dtypes)

iso_code                   object
country                    object
year                        int64
coal_prod_change_pct      float64
coal_prod_change_twh      float64
                           ...
wind_share_energy          object
wind_cons_change_twh       object
wind_consumption           object
wind_elec_per_capita       object
wind_energy_per_capita     object
Length: 128, dtype: object

In [ ]:
df['coal_prod_change_pct'] = pd.to_numeric(df['coal_prod_change_pct'], errors ='coerce')

In [ ]:
df['coal_prod_change_pct'].median()

9.3575

In [ ]:
df['coal_prod_change_pct'].fillna(9.3575,inplace=True)

In [ ]:
print(df)

    iso_code    country  year  coal_prod_change_pct  coal_prod_change_twh  \
0        IDN  Indonesia  1900                9.3575                 0.533
1        IDN  Indonesia  1901                0.9850                 0.016
2        IDN  Indonesia  1902               -6.3410                -0.106
3        IDN  Indonesia  1903                9.8960                 0.155
4        IDN  Indonesia  1904                9.4790                 0.163
..       ...        ...   ...                   ...                   ...
116      IDN  Indonesia  2016               -1.1630               -36.789
117      IDN  Indonesia  2017                1.1070                34.611
118      IDN  Indonesia  2018               20.9270               661.493
119      IDN  Indonesia  2019               10.4680               400.129
120      IDN  Indonesia  2020               -8.7040              -367.529

     gas_prod_change_pct  gas_prod_change_twh  oil_prod_change_pct  \
0                  6.354                0.494               2.9695
1                  6.354                0.000              78.1350
2                  6.354                0.000             -39.3500
3                  6.354                0.000             136.9050
4                  6.354                0.000              12.8140
..                   ...                  ...                  ...
116               -1.421              -10.822               5.3880
117               -3.163              -23.750              -4.2040
118                0.133                0.967              -3.5260
119               -7.168              -52.182              -3.4030
120               -6.556              -44.310              -4.6660

     oil_prod_change_twh  energy_cons_change_pct  ... solar_consumption  \
0                 1.5585                   6.662  ...
1                 2.8260                   6.662  ...
2                -2.5350                   6.662  ...
3                 5.3500                   6.662  ...
4                 1.1860                   6.662  ...
..                   ...                     ...  ...               ...
116              25.4300                   1.144  ...             0.053
117             -20.9100                   4.167  ...             0.073
118             -16.7980                   7.990  ...              0.05
119             -15.6440                   7.238  ...             0.134
120             -20.7200                 -11.782  ...             1.166

    solar_elec_per_capita solar_energy_per_capita wind_share_elec  \
0
1
2
3
4
..                    ...                     ...             ...
116                 0.076                   0.203           0.004
117                 0.113                   0.274             0.0
118                 0.075                   0.186           0.071
119                 0.185                   0.494           0.172
120                 0.183                   4.264           0.171

    wind_cons_change_pct wind_share_energy wind_cons_change_twh  \
0
1
2
3
4
..                   ...               ...                  ...
116               52.819             0.001                0.005
117               -100.0               0.0               -0.014
118                                  0.021                0.467
119              155.465              0.05                0.726
120               -2.292             0.055               -0.027

    wind_consumption wind_elec_per_capita wind_energy_per_capita
0
1
2
3
4
..               ...                  ...                    ...
116            0.014                0.038                  0.055
117              0.0                  0.0                    0.0
118            0.467                 0.71                  1.745
119            1.194                1.774                   4.41
120            1.166                1.718                  4.264

[121 rows x 128 columns]

In [ ]:
df

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,IDN,Indonesia,1900,9.3575,0.533,6.354,0.494,2.9695,1.5585,6.662,...,,,,,,,,,,
1,IDN,Indonesia,1901,0.9850,0.016,6.354,0.000,78.1350,2.8260,6.662,...,,,,,,,,,,
2,IDN,Indonesia,1902,-6.3410,-0.106,6.354,0.000,-39.3500,-2.5350,6.662,...,,,,,,,,,,
3,IDN,Indonesia,1903,9.8960,0.155,6.354,0.000,136.9050,5.3500,6.662,...,,,,,,,,,,
4,IDN,Indonesia,1904,9.4790,0.163,6.354,0.000,12.8140,1.1860,6.662,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,IDN,Indonesia,2016,-1.1630,-36.789,-1.421,-10.822,5.3880,25.4300,1.144,...,0.053,0.076,0.203,0.004,52.819,0.001,0.005,0.014,0.038,0.055
117,IDN,Indonesia,2017,1.1070,34.611,-3.163,-23.750,-4.2040,-20.9100,4.167,...,0.073,0.113,0.274,0.0,-100.0,0.0,-0.014,0.0,0.0,0.0
118,IDN,Indonesia,2018,20.9270,661.493,0.133,0.967,-3.5260,-16.7980,7.990,...,0.05,0.075,0.186,0.071,,0.021,0.467,0.467,0.71,1.745
119,IDN,Indonesia,2019,10.4680,400.129,-7.168,-52.182,-3.4030,-15.6440,7.238,...,0.134,0.185,0.494,0.172,155.465,0.05,0.726,1.194,1.774,4.41
120,IDN,Indonesia,2020,-8.7040,-367.529,-6.556,-44.310,-4.6660,-20.7200,-11.782,...,1.166,0.183,4.264,0.171,-2.292,0.055,-0.027,1.166,1.718,4.264

Warning: Total number of columns (128) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df.isnull().sum()

iso_code                  0
country                   0
year                      0
coal_prod_change_pct      0
coal_prod_change_twh      0
                         ..
wind_share_energy         0
wind_cons_change_twh      0
wind_consumption          0
wind_elec_per_capita      0
wind_energy_per_capita    0
Length: 128, dtype: int64

In [ ]:
df

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,IDN,Indonesia,1900,9.3575,0.533,6.354,0.494,2.9695,1.5585,6.662,...,,,,,,,,,,
1,IDN,Indonesia,1901,0.9850,0.016,6.354,0.000,78.1350,2.8260,6.662,...,,,,,,,,,,
2,IDN,Indonesia,1902,-6.3410,-0.106,6.354,0.000,-39.3500,-2.5350,6.662,...,,,,,,,,,,
3,IDN,Indonesia,1903,9.8960,0.155,6.354,0.000,136.9050,5.3500,6.662,...,,,,,,,,,,
4,IDN,Indonesia,1904,9.4790,0.163,6.354,0.000,12.8140,1.1860,6.662,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,IDN,Indonesia,2016,-1.1630,-36.789,-1.421,-10.822,5.3880,25.4300,1.144,...,0.053,0.076,0.203,0.004,52.819,0.001,0.005,0.014,0.038,0.055
117,IDN,Indonesia,2017,1.1070,34.611,-3.163,-23.750,-4.2040,-20.9100,4.167,...,0.073,0.113,0.274,0.0,-100.0,0.0,-0.014,0.0,0.0,0.0
118,IDN,Indonesia,2018,20.9270,661.493,0.133,0.967,-3.5260,-16.7980,7.990,...,0.05,0.075,0.186,0.071,,0.021,0.467,0.467,0.71,1.745
119,IDN,Indonesia,2019,10.4680,400.129,-7.168,-52.182,-3.4030,-15.6440,7.238,...,0.134,0.185,0.494,0.172,155.465,0.05,0.726,1.194,1.774,4.41
120,IDN,Indonesia,2020,-8.7040,-367.529,-6.556,-44.310,-4.6660,-20.7200,-11.782,...,1.166,0.183,4.264,0.171,-2.292,0.055,-0.027,1.166,1.718,4.264

Warning: Total number of columns (128) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
excel_file_path = 'output.xlsx'

In [ ]:
df.to_excel(excel_file_path,index=False)

In [ ]:
print("Dataset copied to Excel sucessfully")

Dataset copied to Excel sucessfully

In [ ]:
df.head()

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,IDN,Indonesia,1900,9.3575,0.533,6.354,0.494,2.9695,1.5585,6.662,...,,,,,,,,,,
1,IDN,Indonesia,1901,0.9850,0.016,6.354,0.000,78.1350,2.8260,6.662,...,,,,,,,,,,
2,IDN,Indonesia,1902,-6.3410,-0.106,6.354,0.000,-39.3500,-2.5350,6.662,...,,,,,,,,,,
3,IDN,Indonesia,1903,9.8960,0.155,6.354,0.000,136.9050,5.3500,6.662,...,,,,,,,,,,
4,IDN,Indonesia,1904,9.4790,0.163,6.354,0.000,12.8140,1.1860,6.662,...,,,,,,,,,,

In [ ]:
print(df.dtypes)

iso_code                   object
country                    object
year                        int64
coal_prod_change_pct      float64
coal_prod_change_twh      float64
                           ...
wind_share_energy          object
wind_cons_change_twh       object
wind_consumption           object
wind_elec_per_capita       object
wind_energy_per_capita     object
Length: 128, dtype: object

In [ ]:
for column in df.columns:
    print(f"{column}: {df[column].dtype}")

iso_code: object
country: object
year: int64
coal_prod_change_pct: float64
coal_prod_change_twh: float64
gas_prod_change_pct: float64
gas_prod_change_twh: float64
oil_prod_change_pct: float64
oil_prod_change_twh: float64
energy_cons_change_pct: float64
energy_cons_change_twh: object
biofuel_share_elec: object
biofuel_elec_per_capita: object
biofuel_cons_change_pct: object
biofuel_share_energy: object
biofuel_cons_change_twh: object
biofuel_consumption: object
biofuel_cons_per_capita: object
carbon_intensity_elec: object
coal_share_elec: object
coal_cons_change_pct: object
coal_share_energy: object
coal_cons_change_twh: object
coal_consumption: object
coal_elec_per_capita: object
coal_cons_per_capita: object
coal_production: float64
coal_prod_per_capita: float64
electricity_demand: object
biofuel_electricity: object
coal_electricity: object
fossil_electricity: object
gas_electricity: object
hydro_electricity: object
nuclear_electricity: object
oil_electricity: object
other_renewable_exc_biofuel_electricity: object
other_renewable_electricity: object
renewables_electricity: object
solar_electricity: object
wind_electricity: object
electricity_generation: object
greenhouse_gas_emissions: object
energy_per_gdp: object
energy_per_capita: object
fossil_cons_change_pct: object
fossil_share_energy: object
fossil_cons_change_twh: object
fossil_fuel_consumption: object
fossil_energy_per_capita: object
fossil_cons_per_capita: object
fossil_share_elec: object
gdp: object
gas_share_elec: object
gas_cons_change_pct: object
gas_share_energy: object
gas_cons_change_twh: object
gas_consumption: object
gas_elec_per_capita: object
gas_energy_per_capita: object
gas_production: float64
gas_prod_per_capita: float64
hydro_share_elec: object
hydro_cons_change_pct: object
hydro_share_energy: object
hydro_cons_change_twh: object
hydro_consumption: object
hydro_elec_per_capita: object
hydro_energy_per_capita: object
low_carbon_share_elec: object
low_carbon_electricity: object
low_carbon_elec_per_capita: object
low_carbon_cons_change_pct: object
low_carbon_share_energy: object
low_carbon_cons_change_twh: object
low_carbon_consumption: object
low_carbon_energy_per_capita: object
net_elec_imports_share_demand: object
net_elec_imports: object
nuclear_share_elec: object
nuclear_cons_change_pct: object
nuclear_share_energy: object
nuclear_cons_change_twh: object
nuclear_consumption: object
nuclear_elec_per_capita: object
nuclear_energy_per_capita: object
oil_share_elec: object
oil_cons_change_pct: object
oil_share_energy: object
oil_cons_change_twh: object
oil_consumption: object
oil_elec_per_capita: object
oil_energy_per_capita: object
oil_production: float64
oil_prod_per_capita: float64
other_renewables_elec_per_capita_exc_biofuel: object
other_renewables_elec_per_capita: object
other_renewables_cons_change_pct: object
other_renewables_share_energy: object
other_renewables_cons_change_twh: object
other_renewable_consumption: object
other_renewables_share_elec_exc_biofuel: object
other_renewables_share_elec: object
other_renewables_energy_per_capita: object
per_capita_electricity: object
population: int64
primary_energy_consumption: object
renewables_elec_per_capita: object
renewables_share_elec: object
renewables_cons_change_pct: object
renewables_share_energy: object
renewables_cons_change_twh: object
renewables_consumption: object
renewables_energy_per_capita: object
solar_share_elec: object
solar_cons_change_pct: object
solar_share_energy: object
solar_cons_change_twh: object
solar_consumption: object
solar_elec_per_capita: object
solar_energy_per_capita: object
wind_share_elec: object
wind_cons_change_pct: object
wind_share_energy: object
wind_cons_change_twh: object
wind_consumption: object
wind_elec_per_capita: object
wind_energy_per_capita: object

In [ ]:
missing_values = df.isnull().sum()

In [ ]:
print("Missing values in each column:")
print(missing_values)

Missing values in each column:
iso_code                  0
country                   0
year                      0
coal_prod_change_pct      0
coal_prod_change_twh      0
                         ..
wind_share_energy         0
wind_cons_change_twh      0
wind_consumption          0
wind_elec_per_capita      0
wind_energy_per_capita    0
Length: 128, dtype: int64

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
print("Missing values in each column:")
print(missing_values)

Missing values in each column:
iso_code                  0
country                   0
year                      0
coal_prod_change_pct      0
coal_prod_change_twh      0
                         ..
wind_share_energy         0
wind_cons_change_twh      0
wind_consumption          0
wind_elec_per_capita      0
wind_energy_per_capita    0
Length: 128, dtype: int64

In [ ]:
missing_values.to_csv('missing_values_info.csv')

In [ ]:
print("Missing values information written to 'missing_values_info.csv' file.")

Missing values information written to 'missing_values_info.csv' file.

In [ ]:
empty_spaces_count = df.isnull().sum()

In [ ]:
print("Number of empty spaces in each column:")
print(empty_spaces_count)

Number of empty spaces in each column:
iso_code                  0
country                   0
year                      0
coal_prod_change_pct      0
coal_prod_change_twh      0
                         ..
wind_share_energy         0
wind_cons_change_twh      0
wind_consumption          0
wind_elec_per_capita      0
wind_energy_per_capita    0
Length: 128, dtype: int64

In [ ]:
df['biofuel_share_elec'] = pd.to_numeric(df['biofuel_share_elec'], errors ='coerce')
df['biofuel_elec_per_capita'] = pd.to_numeric(df['biofuel_elec_per_capita'], errors ='coerce')
df['biofuel_cons_change_pct'] = pd.to_numeric(df['biofuel_cons_change_pct'], errors ='coerce')

In [ ]:
df['biofuel_share_elec'].median()
df['biofuel_elec_per_capita'].median()
df['biofuel_share_elec'].median()

5.182

In [ ]:
df['biofuel_share_elec'].median()

5.182

In [ ]:
df['biofuel_elec_per_capita'].median()

38.438

In [ ]:
df['biofuel_cons_change_pct'].median()

34.614

In [ ]:
df['biofuel_share_elec'].fillna(5.182,inplace=True)

In [ ]:
df

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,energy_cons_change_twh,biofuel_share_elec,biofuel_elec_per_capita,biofuel_cons_change_pct,biofuel_share_energy,biofuel_cons_change_twh,biofuel_consumption,biofuel_cons_per_capita,carbon_intensity_elec,coal_share_elec,coal_cons_change_pct,coal_share_energy,coal_cons_change_twh,coal_consumption,coal_elec_per_capita,coal_cons_per_capita,coal_production,coal_prod_per_capita,electricity_demand,biofuel_electricity,coal_electricity,fossil_electricity,gas_electricity,hydro_electricity,nuclear_electricity,oil_electricity,other_renewable_exc_biofuel_electricity,other_renewable_electricity,renewables_electricity,solar_electricity,wind_electricity,electricity_generation,greenhouse_gas_emissions,energy_per_gdp,energy_per_capita,fossil_cons_change_pct,fossil_share_energy,fossil_cons_change_twh,fossil_fuel_consumption,fossil_energy_per_capita,fossil_cons_per_capita,fossil_share_elec,gdp,gas_share_elec,gas_cons_change_pct,gas_share_energy,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_energy_per_capita,gas_production,gas_prod_per_capita,hydro_share_elec,hydro_cons_change_pct,hydro_share_energy,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_energy_per_capita,low_carbon_share_elec,low_carbon_electricity,low_carbon_elec_per_capita,low_carbon_cons_change_pct,low_carbon_share_energy,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_energy_per_capita,net_elec_imports_share_demand,net_elec_imports,nuclear_share_elec,nuclear_cons_change_pct,nuclear_share_energy,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_energy_per_capita,oil_share_elec,oil_cons_change_pct,oil_share_energy,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_energy_per_capita,oil_production,oil_prod_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_elec_per_capita,other_renewables_cons_change_pct,other_renewables_share_energy,other_renewables_cons_change_twh,other_renewable_consumption,other_renewables_share_elec_exc_biofuel,other_renewables_share_elec,other_renewables_energy_per_capita,per_capita_electricity,population,primary_energy_consumption,renewables_elec_per_capita,renewables_share_elec,renewables_cons_change_pct,renewables_share_energy,renewables_cons_change_twh,renewables_consumption,renewables_energy_per_capita,solar_share_elec,solar_cons_change_pct,solar_share_energy,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,IDN,Indonesia,1900,9.3575,0.533,6.354,0.494,2.9695,1.5585,6.662,NaN,5.182,38.438,34.614,,,,,,,,,,,,,1.653,43.297,,,,,,,,,,,,,,,,,,,,,,,,,51910100000.0,,,,,,,,0.000,0.000,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,3.617,94.759,,,,,,,,,,,38169857,,,,,,,,,,,,,,,,,,,,,,
1,IDN,Indonesia,1901,0.9850,0.016,6.354,0.000,78.1350,2.8260,6.662,NaN,5.182,38.438,34.614,,,,,,,,,,,,,1.669,43.170,,,,,,,,,,,,,,,,,,,,,,,,,51089575000.0,,,,,,,,0.000,0.000,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,6.443,166.664,,,,,,,,,,,38658803,,,,,,,,,,,,,,,,,,,,,,
2,IDN,Indonesia,1902,-6.3410,-0.106,6.354,0.000,-39.3500,-2.5350,6.662,NaN,5.182,38.438,34.614,,,,,,,,,,,,,1.563,39.922,,,,,,,,,,,,,,,,,,,,,,,,,50067220000.0,,,,,,,,0.000,0.000,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,3.908,99.805,,,,,,,,,,,39153251,,,,,,,,,,,,,,,,,,,,,,
3,IDN,Indonesia,1903,9.8960,0.155,6.354,0.000,136.9050,5.3500,6.662,NaN,5.182,38.438,34.614,,,,,,,,,,,,,1.718,43.339,,,,,,,,,,,,,,,,,,,,,,,,,52836520000.0,,,,,,,,0.000,0.000,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,9.257,233.565,,,,,,,,,,,39635616,,,,,,,,,,,,,,,,,,,,,,
4,IDN,Indonesia,1904,9.4790,0.163,6.354,0.000,12.8140,1.1860,6.662,NaN,5.182,38.438,34.614,,,,,,,,,,,,,1.881,46.891,,,,,,,,,,,,,,,,,,,,,,,,,53544038000.0,,,,,,,,0.000,0.000,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,10.444,260.407,,,,,,,,,,,40105530,,,,,,,,,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,IDN,Indonesia,2016,-1.1630,-36.789,-1.421,-10.822,5.3880,25.4300,1.144,22.548,4.422,41.865,204.804,1.421,19.03,28.321,108.279,641.36,54.67,4.303,31.135,25.597,620.408,517.594,2371.987,3126.366,11952.934,248.32,10.95,135.38,217.97,61.79,18.68,0.0,20.8,,10.951,29.655,0.02,0.01,247.63,158.82,0.716,7618.335,-0.539,94.836,-10.249,1889.729,7224.94,833.358,88.022,2783160000000.0,24.953,-2.458,22.398,-11.248,446.308,236.24,1706.355,750.800,2870.508,7.544,35.121,2.357,12.208,46.969,71.419,179.573,11.975,29.655,113.378,46.785,5.164,32.797,102.896,393.401,0.278,0.69,0.0,,0.0,0.0,0.0,0.0,0.0,8.4,-2.902,41.303,-24.598,823.012,79.524,3146.599,497.372,1901.585,,41.868,5.818,1.382,1.514,27.539,,4.422,105.291,946.756,261556384,1992.624,113.378,11.975,46.785,5.164,32.797,102.896,393.401,0.008,296.95,0.003,0.04,0.053,0.076,0.203,0.004,52.819,0.001,0.005,0.014,0.038,0.055
117,IDN,Indonesia,2017,1.1070,34.611,-3.163,-23.750,-4.2040,-20.9100,4.167,83.026,5.134,49.348,-14.073,1.172,-3.986,24.335,91.953,650.024,58.17,7.156,32.029,44.398,664.806,559.076,2512.012,3160.977,11943.946,255.48,13.06,147.96,222.64,55.83,18.63,0.0,18.85,,13.059,31.72,0.03,0.0,254.36,165.34,0.71,7842.971,4.354,95.007,82.285,1972.015,7451.379,841.259,87.529,2924270000000.0,21.949,-3.171,20.82,-14.154,432.153,210.957,1632.919,727.050,2747.203,7.324,-0.825,2.244,-0.388,46.581,70.395,176.009,12.471,31.72,119.858,0.719,4.993,0.74,103.637,391.598,0.438,1.12,0.0,,0.0,0.0,0.0,0.0,0.0,7.411,6.323,42.158,52.042,875.054,71.226,3306.448,476.461,1800.339,,49.344,18.549,1.573,5.108,32.648,,5.134,123.361,961.115,264650976,2075.65,119.858,12.471,0.719,4.993,0.74,103.637,391.598,0.012,36.933,0.003,0.02,0.073,0.113,0.274,0.0,-100.0,0.0,-0.014,0.0,0.0,0.0
118,IDN,Indonesia,2018,20.9270,661.493,0.133,0.967,-3.5260,-16.7980,7.990,165.835,5.371,53.536,44.016,1.564,10.711,35.047,130.933,658.333,59.978,18.602,35.177,123.671,788.476,597.787,2945.699,3822.470,14280.503,268.28,14.33,160.01,235.41,57.45,16.83,0.0,17.95,,14.33,31.365,0.02,0.19,266.78,175.63,0.729,8374.044,7.935,94.959,156.47,2128.485,7951.884,879.477,88.241,3075460000000.0,21.535,3.039,19.866,13.132,445.286,214.63,1663.561,728.017,2719.824,6.309,-10.216,1.866,-4.759,41.822,62.876,156.246,11.757,31.365,117.179,9.036,5.041,9.365,113.002,422.168,0.559,1.5,0.0,,0.0,0.0,0.0,0.0,0.0,6.728,2.248,39.916,19.667,894.721,67.06,3342.624,459.664,1717.274,,53.536,9.091,1.589,2.968,35.616,,5.371,133.057,996.673,267670560,2241.485,117.179,11.757,9.036,5.041,9.365,113.002,422.168,0.007,-31.59,0.002,-0.023,0.05,0.075,0.186,0.071,,0.021,0.467,0.467,0.71,1.745
119,IDN,Indonesia,2019,10.4680,400.129,-7.168,-52.182,-3.4030,-15.6440,7.238,162.229,5.147,53.025,69.163,2.466,24.239,59.286,219.071,662.578,62.582,20.28,39.455,159.903,948.379,644.765,3504.399,4222.599,15603.106,280.5,14.35,174.49,247.39,62.32,16.55,0.0,10.58,,14.346,31.428,0.05,0.48,278.82,184.74,,8882.066,6.489,94.296,138.122,2266.607,8375.437,914.141,88.727,,22.351,-1.366,18.272,-6.083,439.203,230.281,1622.918,675.834,2497.304,5.936,-2.035,1.705,-0.851,40.972,61.155,151.396,11.272,31.428,116.131,21.333,5.704,24.107,137.109,506.637,0.599,1.68,0.0,,0.0,0.0,0.0,0.0,0.0,3.795,-1.754,36.569,-15.698,879.024,39.095,3248.12,444.020,1640.715,,53.011,-0.258,1.478,-0.092,35.524,,5.145,131.266,1030.28,270625568,2403.714,116.131,11.272,21.333,5.704,24.107,137.109,506.637,0.018,169.139,0.006,0.084,0.134,0.185,0.494,0.172,155.465,0.05,0.726,1.194,1.774,4.41
120,IDN,Indonesia,2020,-8.7040,-367.529,-6.556,-44.310,-4.6660,-20.7200,-11.782,-283.195,5.780,58.057,2.796,2.874,1.658,60.944,222.811,663.488,65.828,-4.638,42.65,-43.986,904.393,661.259,3306.455,3855.071,14094.106,276.31,15.88,180.87,238.91,51.28,19.45,0.0,6.76,,15.882,36.282,0.05,0.47,274.76,182.3,,7752.6,-13.083,92.905,-296.543,1970.065,7202.54,873.453,86.952,,18.664,-5.446,19.584,-23.92,415.283,187.479,1518.273,631.525,2308.849,7.079,17.146,2.263,7.025,47.996,71.109,175.474,13.205,36.282,132.647,9.735,7.095,13.347,150.456,550.067,0.561,1.55,0.0,,0.0,0.0,0.0,0.0,0.0,2.46,-26.01,30.671,-228.637,650.387,24.715,2377.812,423.299,1547.579,,58.065,10.302,1.848,3.66,39.183,,5.78,143.254,1004.52,273523616,2120.519,132.647,13.205,9.735,7.095,13.347,150.456,550.067,0.018,772.136,0.055,1.032,1.166,0.183,4.264,0.171,-2.292,0.055,-0.027,1.166,1.718,4.264

In [ ]:
df['biofuel_elec_per_capita'].fillna(38.438,inplace=True)

In [ ]:
df['biofuel_cons_change_pct'].fillna(34.614,inplace=True)

In [ ]:
df = df.apply(pd.to_numeric, errors='coerce')

In [ ]:
print(df.dtypes)

iso_code                  float64
country                   float64
year                        int64
coal_prod_change_pct      float64
coal_prod_change_twh      float64
                           ...
wind_share_energy         float64
wind_cons_change_twh      float64
wind_consumption          float64
wind_elec_per_capita      float64
wind_energy_per_capita    float64
Length: 128, dtype: object

In [ ]:
for column in df.columns:
    print(f"{column}: {df[column].dtype}")

iso_code: float64
country: float64
year: int64
coal_prod_change_pct: float64
coal_prod_change_twh: float64
gas_prod_change_pct: float64
gas_prod_change_twh: float64
oil_prod_change_pct: float64
oil_prod_change_twh: float64
energy_cons_change_pct: float64
energy_cons_change_twh: float64
biofuel_share_elec: float64
biofuel_elec_per_capita: float64
biofuel_cons_change_pct: float64
biofuel_share_energy: float64
biofuel_cons_change_twh: float64
biofuel_consumption: float64
biofuel_cons_per_capita: float64
carbon_intensity_elec: float64
coal_share_elec: float64
coal_cons_change_pct: float64
coal_share_energy: float64
coal_cons_change_twh: float64
coal_consumption: float64
coal_elec_per_capita: float64
coal_cons_per_capita: float64
coal_production: float64
coal_prod_per_capita: float64
electricity_demand: float64
biofuel_electricity: float64
coal_electricity: float64
fossil_electricity: float64
gas_electricity: float64
hydro_electricity: float64
nuclear_electricity: float64
oil_electricity: float64
other_renewable_exc_biofuel_electricity: float64
other_renewable_electricity: float64
renewables_electricity: float64
solar_electricity: float64
wind_electricity: float64
electricity_generation: float64
greenhouse_gas_emissions: float64
energy_per_gdp: float64
energy_per_capita: float64
fossil_cons_change_pct: float64
fossil_share_energy: float64
fossil_cons_change_twh: float64
fossil_fuel_consumption: float64
fossil_energy_per_capita: float64
fossil_cons_per_capita: float64
fossil_share_elec: float64
gdp: float64
gas_share_elec: float64
gas_cons_change_pct: float64
gas_share_energy: float64
gas_cons_change_twh: float64
gas_consumption: float64
gas_elec_per_capita: float64
gas_energy_per_capita: float64
gas_production: float64
gas_prod_per_capita: float64
hydro_share_elec: float64
hydro_cons_change_pct: float64
hydro_share_energy: float64
hydro_cons_change_twh: float64
hydro_consumption: float64
hydro_elec_per_capita: float64
hydro_energy_per_capita: float64
low_carbon_share_elec: float64
low_carbon_electricity: float64
low_carbon_elec_per_capita: float64
low_carbon_cons_change_pct: float64
low_carbon_share_energy: float64
low_carbon_cons_change_twh: float64
low_carbon_consumption: float64
low_carbon_energy_per_capita: float64
net_elec_imports_share_demand: float64
net_elec_imports: float64
nuclear_share_elec: float64
nuclear_cons_change_pct: float64
nuclear_share_energy: float64
nuclear_cons_change_twh: float64
nuclear_consumption: float64
nuclear_elec_per_capita: float64
nuclear_energy_per_capita: float64
oil_share_elec: float64
oil_cons_change_pct: float64
oil_share_energy: float64
oil_cons_change_twh: float64
oil_consumption: float64
oil_elec_per_capita: float64
oil_energy_per_capita: float64
oil_production: float64
oil_prod_per_capita: float64
other_renewables_elec_per_capita_exc_biofuel: float64
other_renewables_elec_per_capita: float64
other_renewables_cons_change_pct: float64
other_renewables_share_energy: float64
other_renewables_cons_change_twh: float64
other_renewable_consumption: float64
other_renewables_share_elec_exc_biofuel: float64
other_renewables_share_elec: float64
other_renewables_energy_per_capita: float64
per_capita_electricity: float64
population: int64
primary_energy_consumption: float64
renewables_elec_per_capita: float64
renewables_share_elec: float64
renewables_cons_change_pct: float64
renewables_share_energy: float64
renewables_cons_change_twh: float64
renewables_consumption: float64
renewables_energy_per_capita: float64
solar_share_elec: float64
solar_cons_change_pct: float64
solar_share_energy: float64
solar_cons_change_twh: float64
solar_consumption: float64
solar_elec_per_capita: float64
solar_energy_per_capita: float64
wind_share_elec: float64
wind_cons_change_pct: float64
wind_share_energy: float64
wind_cons_change_twh: float64
wind_consumption: float64
wind_elec_per_capita: float64
wind_energy_per_capita: float64

In [ ]:
median_values = df.median()

In [ ]:
print("Median values for each column:")
print(median_values)

Median values for each column:
iso_code                        NaN
country                         NaN
year                      1960.0000
coal_prod_change_pct         9.3575
coal_prod_change_twh         0.5330
                            ...
wind_share_energy            0.0000
wind_cons_change_twh         0.0000
wind_consumption             0.0000
wind_elec_per_capita         0.0000
wind_energy_per_capita       0.0000
Length: 128, dtype: float64

In [ ]:
df.fillna(median_values,inplace=True)

In [ ]:
df

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,energy_cons_change_twh,biofuel_share_elec,biofuel_elec_per_capita,biofuel_cons_change_pct,biofuel_share_energy,biofuel_cons_change_twh,biofuel_consumption,biofuel_cons_per_capita,carbon_intensity_elec,coal_share_elec,coal_cons_change_pct,coal_share_energy,coal_cons_change_twh,coal_consumption,coal_elec_per_capita,coal_cons_per_capita,coal_production,coal_prod_per_capita,electricity_demand,biofuel_electricity,coal_electricity,fossil_electricity,gas_electricity,hydro_electricity,nuclear_electricity,oil_electricity,other_renewable_exc_biofuel_electricity,other_renewable_electricity,renewables_electricity,solar_electricity,wind_electricity,electricity_generation,greenhouse_gas_emissions,energy_per_gdp,energy_per_capita,fossil_cons_change_pct,fossil_share_energy,fossil_cons_change_twh,fossil_fuel_consumption,fossil_energy_per_capita,fossil_cons_per_capita,fossil_share_elec,gdp,gas_share_elec,gas_cons_change_pct,gas_share_energy,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_energy_per_capita,gas_production,gas_prod_per_capita,hydro_share_elec,hydro_cons_change_pct,hydro_share_energy,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_energy_per_capita,low_carbon_share_elec,low_carbon_electricity,low_carbon_elec_per_capita,low_carbon_cons_change_pct,low_carbon_share_energy,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_energy_per_capita,net_elec_imports_share_demand,net_elec_imports,nuclear_share_elec,nuclear_cons_change_pct,nuclear_share_energy,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_energy_per_capita,oil_share_elec,oil_cons_change_pct,oil_share_energy,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_energy_per_capita,oil_production,oil_prod_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_elec_per_capita,other_renewables_cons_change_pct,other_renewables_share_energy,other_renewables_cons_change_twh,other_renewable_consumption,other_renewables_share_elec_exc_biofuel,other_renewables_share_elec,other_renewables_energy_per_capita,per_capita_electricity,population,primary_energy_consumption,renewables_elec_per_capita,renewables_share_elec,renewables_cons_change_pct,renewables_share_energy,renewables_cons_change_twh,renewables_consumption,renewables_energy_per_capita,solar_share_elec,solar_cons_change_pct,solar_share_energy,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,NaN,NaN,1900,9.3575,0.533,6.354,0.494,2.9695,1.5585,6.662,29.305,5.182,38.438,34.614,0.063,0.001,0.911,3.973,616.801,39.9025,11.759,7.082,5.761,53.224,204.1965,278.689,1.653,43.297,169.74,9.40,44.695,94.80,33.619,7.696,0.0,14.832,NaN,1.1095,9.0905,0.00,0.00,110.585,99.18,0.811,3955.7195,6.542,96.5535,31.633,720.1495,3803.6835,433.140,85.7115,5.191010e+10,26.9395,3.856,24.3235,7.178,222.1435,157.4445,1173.3235,0.000,0.000,8.7945,4.872,2.310,0.466,21.378,40.6525,111.831,14.2915,9.0905,47.636,9.036,3.4465,1.577,25.251,132.322,0.000,0.00,0.0,NaN,0.0,0.0,0.0,0.0,0.0,13.4785,5.189,59.3455,14.619,444.7815,73.132,2344.101,3.617,94.759,NaN,5.999,5.458,0.476,0.000,3.0825,NaN,4.570,16.664,505.288,38169857,748.919,47.636,14.2915,9.036,3.4465,1.577,25.251,132.322,0.000,64.4255,0.000,0.000,0.000,0.000,0.000,0.000,-1.441,0.000,0.000,0.000,0.000,0.000
1,NaN,NaN,1901,0.9850,0.016,6.354,0.000,78.1350,2.8260,6.662,29.305,5.182,38.438,34.614,0.063,0.001,0.911,3.973,616.801,39.9025,11.759,7.082,5.761,53.224,204.1965,278.689,1.669,43.170,169.74,9.40,44.695,94.80,33.619,7.696,0.0,14.832,NaN,1.1095,9.0905,0.00,0.00,110.585,99.18,0.811,3955.7195,6.542,96.5535,31.633,720.1495,3803.6835,433.140,85.7115,5.108958e+10,26.9395,3.856,24.3235,7.178,222.1435,157.4445,1173.3235,0.000,0.000,8.7945,4.872,2.310,0.466,21.378,40.6525,111.831,14.2915,9.0905,47.636,9.036,3.4465,1.577,25.251,132.322,0.000,0.00,0.0,NaN,0.0,0.0,0.0,0.0,0.0,13.4785,5.189,59.3455,14.619,444.7815,73.132,2344.101,6.443,166.664,NaN,5.999,5.458,0.476,0.000,3.0825,NaN,4.570,16.664,505.288,38658803,748.919,47.636,14.2915,9.036,3.4465,1.577,25.251,132.322,0.000,64.4255,0.000,0.000,0.000,0.000,0.000,0.000,-1.441,0.000,0.000,0.000,0.000,0.000
2,NaN,NaN,1902,-6.3410,-0.106,6.354,0.000,-39.3500,-2.5350,6.662,29.305,5.182,38.438,34.614,0.063,0.001,0.911,3.973,616.801,39.9025,11.759,7.082,5.761,53.224,204.1965,278.689,1.563,39.922,169.74,9.40,44.695,94.80,33.619,7.696,0.0,14.832,NaN,1.1095,9.0905,0.00,0.00,110.585,99.18,0.811,3955.7195,6.542,96.5535,31.633,720.1495,3803.6835,433.140,85.7115,5.006722e+10,26.9395,3.856,24.3235,7.178,222.1435,157.4445,1173.3235,0.000,0.000,8.7945,4.872,2.310,0.466,21.378,40.6525,111.831,14.2915,9.0905,47.636,9.036,3.4465,1.577,25.251,132.322,0.000,0.00,0.0,NaN,0.0,0.0,0.0,0.0,0.0,13.4785,5.189,59.3455,14.619,444.7815,73.132,2344.101,3.908,99.805,NaN,5.999,5.458,0.476,0.000,3.0825,NaN,4.570,16.664,505.288,39153251,748.919,47.636,14.2915,9.036,3.4465,1.577,25.251,132.322,0.000,64.4255,0.000,0.000,0.000,0.000,0.000,0.000,-1.441,0.000,0.000,0.000,0.000,0.000
3,NaN,NaN,1903,9.8960,0.155,6.354,0.000,136.9050,5.3500,6.662,29.305,5.182,38.438,34.614,0.063,0.001,0.911,3.973,616.801,39.9025,11.759,7.082,5.761,53.224,204.1965,278.689,1.718,43.339,169.74,9.40,44.695,94.80,33.619,7.696,0.0,14.832,NaN,1.1095,9.0905,0.00,0.00,110.585,99.18,0.811,3955.7195,6.542,96.5535,31.633,720.1495,3803.6835,433.140,85.7115,5.283652e+10,26.9395,3.856,24.3235,7.178,222.1435,157.4445,1173.3235,0.000,0.000,8.7945,4.872,2.310,0.466,21.378,40.6525,111.831,14.2915,9.0905,47.636,9.036,3.4465,1.577,25.251,132.322,0.000,0.00,0.0,NaN,0.0,0.0,0.0,0.0,0.0,13.4785,5.189,59.3455,14.619,444.7815,73.132,2344.101,9.257,233.565,NaN,5.999,5.458,0.476,0.000,3.0825,NaN,4.570,16.664,505.288,39635616,748.919,47.636,14.2915,9.036,3.4465,1.577,25.251,132.322,0.000,64.4255,0.000,0.000,0.000,0.000,0.000,0.000,-1.441,0.000,0.000,0.000,0.000,0.000
4,NaN,NaN,1904,9.4790,0.163,6.354,0.000,12.8140,1.1860,6.662,29.305,5.182,38.438,34.614,0.063,0.001,0.911,3.973,616.801,39.9025,11.759,7.082,5.761,53.224,204.1965,278.689,1.881,46.891,169.74,9.40,44.695,94.80,33.619,7.696,0.0,14.832,NaN,1.1095,9.0905,0.00,0.00,110.585,99.18,0.811,3955.7195,6.542,96.5535,31.633,720.1495,3803.6835,433.140,85.7115,5.354404e+10,26.9395,3.856,24.3235,7.178,222.1435,157.4445,1173.3235,0.000,0.000,8.7945,4.872,2.310,0.466,21.378,40.6525,111.831,14.2915,9.0905,47.636,9.036,3.4465,1.577,25.251,132.322,0.000,0.00,0.0,NaN,0.0,0.0,0.0,0.0,0.0,13.4785,5.189,59.3455,14.619,444.7815,73.132,2344.101,10.444,260.407,NaN,5.999,5.458,0.476,0.000,3.0825,NaN,4.570,16.664,505.288,40105530,748.919,47.636,14.2915,9.036,3.4465,1.577,25.251,132.322,0.000,64.4255,0.000,0.000,0.000,0.000,0.000,0.000,-1.441,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,NaN,NaN,2016,-1.1630,-36.789,-1.421,-10.822,5.3880,25.4300,1.144,22.548,4.422,41.865,204.804,1.421,19.030,28.321,108.279,641.360,54.6700,4.303,31.135,25.597,620.408,517.5940,2371.987,3126.366,11952.934,248.32,10.95,135.380,217.97,61.790,18.680,0.0,20.800,NaN,10.9510,29.6550,0.02,0.01,247.630,158.82,0.716,7618.3350,-0.539,94.8360,-10.249,1889.7290,7224.9400,833.358,88.0220,2.783160e+12,24.9530,-2.458,22.3980,-11.248,446.3080,236.2400,1706.3550,750.800,2870.508,7.5440,35.121,2.357,12.208,46.969,71.4190,179.573,11.9750,29.6550,113.378,46.785,5.1640,32.797,102.896,393.401,0.278,0.69,0.0,NaN,0.0,0.0,0.0,0.0,0.0,8.4000,-2.902,41.3030,-24.598,823.0120,79.524,3146.599,497.372,1901.585,NaN,41.868,5.818,1.382,1.514,27.5390,NaN,4.422,105.291,946.756,261556384,1992.624,113.378,11.9750,46.785,5.1640,32.797,102.896,393.401,0.008,296.9500,0.003,0.040,0.053,0.076,0.203,0.004,52.819,0.001,0.005,0.014,0.038,0.055
117,NaN,NaN,2017,1.1070,34.611,-3.163,-23.750,-4.2040,-20.9100,4.167,83.026,5.134,49.348,-14.073,1.172,-3.986,24.335,91.953,650.024,58.1700,7.156,32.029,44.398,664.806,559.0760,2512.012,3160.977,11943.946,255.48,13.06,147.960,222.64,55.830,18.630,0.0,18.850,NaN,13.0590,31.7200,0.03,0.00,254.360,165.34,0.710,7842.9710,4.354,95.0070,82.285,1972.0150,7451.3790,841.259,87.5290,2.924270e+12,21.9490,-3.171,20.8200,-14.154,432.1530,210.9570,1632.9190,727.050,2747.203,7.3240,-0.825,2.244,-0.388,46.581,70.3950,176.009,12.4710,31.7200,119.858,0.719,4.9930,0.740,103.637,391.598,0.438,1.12,0.0,NaN,0.0,0.0,0.0,0.0,0.0,7.4110,6.323,42.1580,52.042,875.0540,71.226,3306.448,476.461,1800.339,NaN,49.344,18.549,1.573,5.108,32.6480,NaN,5.134,123.361,961.115,264650976,2075.650,119.858,12.4710,0.719,4.9930,0.740,103.637,391.598,0.012,36.9330,0.003,0.020,0.073,0.113,0.274,0.000,-100.000,0.000,-0.014,0.000,0.000,0.000
118,NaN,NaN,2018,20.9270,661.493,0.133,0.967,-3.5260,-16.7980,7.990,165.835,5.371,53.536,44.016,1.564,10.711,35.047,130.933,658.333,59.9780,18.602,35.177,123.671,788.476,597.7870,2945.699,3822.470,14280.503,268.28,14.33,160.010,235.41,57.450,16.830,0.0,17.950,NaN,14.3300,31.3650,0.02,0.19,266.780,175.63,0.729,8374.0440,7.935,94.9590,156.470,2128.4850,7951.8840,879.477,88.2410,3.075460e+12,21.5350,3.039,19.8660,13.132,445.2860,214.6300,1663.5610,728.017,2719.824,6.3090,-10.216,1.866,-4.759,41.822,62.8760,156.246,11.7570,31.3650,117.179,9.036,5.0410,9.365,113.002,422.168,0.559,1.50,0.0,NaN,0.0,0.0,0.0,0.0,0.0,6.7280,2.248,39.9160,19.667,894.7210,67.060,3342.624,459.664,1717.274,NaN,53.536,9.091,1.589,2.968,35.6160,NaN,5.371,133.057,996.673,267670560,2241.485,117.179,11.7570,9.036,5.0410,9.365,113.002,422.168,0.007,-31.5900,0.002,-0.023,0.050,0.075,0.186,0.071,-1.441,0.021,0.467,0.467,0.710,1.745
119,NaN,NaN,2019,10.4680,400.129,-7.168,-52.182,-3.4030,-15.6440,7.238,162.229,5.147,53.025,69.163,2.466,24.239,59.286,219.071,662.578,62.5820,20.280,39.455,159.903,948.379,644.7650,3504.399,4222.599,15603.106,280.50,14.35,174.490,247.39,62.320,16.550,0.0,10.580,NaN,14.3460,31.4280,0.05,0.48,278.820,184.74,0.811,8882.0660,6.489,94.2960,138.122,2266.6070,8375.4370,914.141,88.7270,1.632345e+11,22.3510,-1.366,18.2720,-6.083,439.2030,230.2810,1622.9180,675.834,2497.304,5.9360,-2.035,1.705,-0.851,40.972,61.1550,151.396,11.2720,31.4280,116.131,21.333,5.7040,24.107,137.109,506.637,0.599,1.68,0.0,NaN,0.0,0.0,0.0,0.0,0.0,3.7950,-1.754,36.5690,-15.698,879.0240,39.095,3248.120,444.020,1640.715,NaN,53.011,-0.258,1.478,-0.092,35.5240,NaN,5.145,131.266,1030.280,270625568,2403.714,116.131,11.2720,21.333,5.7040,24.107,137.109,506.637,0.018,169.1390,0.006,0.084,0.134,0.185,0.494,0.172,155.465,0.050,0.726,1.194,1.774,4.410
120,NaN,NaN,2020,-8.7040,-367.529,-6.556,-44.310,-4.6660,-20.7200,-11.782,-283.195,5.780,58.057,2.796,2.874,1.658,60.944,222.811,663.488,65.8280,-4.638,42.650,-43.986,904.393,661.2590,3306.455,3855.071,14094.106,276.31,15.88,180.870,238.91,51.280,19.450,0.0,6.760,NaN,15.8820,36.2820,0.05,0.47,274.760,182.30,0.811,7752.6000,-13.083,92.9050,-296.543,1970.0650,7202.5400,873.453,86.9520,1.632345e+11,18.6640,-5.446,19.5840,-23.920,415.2830,187.4790,1518.2730,631.525,2308.849,7.0790,17.146,2.263,7.025,47.996,71.1090,175.474,13.2050,36.2820,132.647,9.735,7.0950,13.347,150.456,550.067,0.561,1.55,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2.4600,-26.010,30.6710,-228.637,650.3870,24.715,2377.812,423.299,1547.579,NaN,58.065,10.302,1.848,3.660,39.1830,NaN,5.780,143.254,1004.520,273523616,2120.519,132.647,13.2050,9.735,7.0950,13.347,150.456,550.067,0.018,772.1360,0.055,1.032,1.166,0.183,4.264,0.171,-2.292,0.055,-0.027,1.166,1.718,4.264

In [ ]:
df

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,energy_cons_change_twh,biofuel_share_elec,biofuel_elec_per_capita,biofuel_cons_change_pct,biofuel_share_energy,biofuel_cons_change_twh,biofuel_consumption,biofuel_cons_per_capita,carbon_intensity_elec,coal_share_elec,coal_cons_change_pct,coal_share_energy,coal_cons_change_twh,coal_consumption,coal_elec_per_capita,coal_cons_per_capita,coal_production,coal_prod_per_capita,electricity_demand,biofuel_electricity,coal_electricity,fossil_electricity,gas_electricity,hydro_electricity,nuclear_electricity,oil_electricity,other_renewable_exc_biofuel_electricity,other_renewable_electricity,renewables_electricity,solar_electricity,wind_electricity,electricity_generation,greenhouse_gas_emissions,energy_per_gdp,energy_per_capita,fossil_cons_change_pct,fossil_share_energy,fossil_cons_change_twh,fossil_fuel_consumption,fossil_energy_per_capita,fossil_cons_per_capita,fossil_share_elec,gdp,gas_share_elec,gas_cons_change_pct,gas_share_energy,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_energy_per_capita,gas_production,gas_prod_per_capita,hydro_share_elec,hydro_cons_change_pct,hydro_share_energy,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_energy_per_capita,low_carbon_share_elec,low_carbon_electricity,low_carbon_elec_per_capita,low_carbon_cons_change_pct,low_carbon_share_energy,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_energy_per_capita,net_elec_imports_share_demand,net_elec_imports,nuclear_share_elec,nuclear_cons_change_pct,nuclear_share_energy,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_energy_per_capita,oil_share_elec,oil_cons_change_pct,oil_share_energy,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_energy_per_capita,oil_production,oil_prod_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_elec_per_capita,other_renewables_cons_change_pct,other_renewables_share_energy,other_renewables_cons_change_twh,other_renewable_consumption,other_renewables_share_elec_exc_biofuel,other_renewables_share_elec,other_renewables_energy_per_capita,per_capita_electricity,population,primary_energy_consumption,renewables_elec_per_capita,renewables_share_elec,renewables_cons_change_pct,renewables_share_energy,renewables_cons_change_twh,renewables_consumption,renewables_energy_per_capita,solar_share_elec,solar_cons_change_pct,solar_share_energy,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_energy_per_capita,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,NaN,NaN,1900,9.3575,0.533,6.354,0.494,2.9695,1.5585,6.662,29.305,5.182,38.438,34.614,0.063,0.001,0.911,3.973,616.801,39.9025,11.759,7.082,5.761,53.224,204.1965,278.689,1.653,43.297,169.74,9.40,44.695,94.80,33.619,7.696,0.0,14.832,NaN,1.1095,9.0905,0.00,0.00,110.585,99.18,0.811,3955.7195,6.542,96.5535,31.633,720.1495,3803.6835,433.140,85.7115,5.191010e+10,26.9395,3.856,24.3235,7.178,222.1435,157.4445,1173.3235,0.000,0.000,8.7945,4.872,2.310,0.466,21.378,40.6525,111.831,14.2915,9.0905,47.636,9.036,3.4465,1.577,25.251,132.322,0.000,0.00,0.0,NaN,0.0,0.0,0.0,0.0,0.0,13.4785,5.189,59.3455,14.619,444.7815,73.132,2344.101,3.617,94.759,NaN,5.999,5.458,0.476,0.000,3.0825,NaN,4.570,16.664,505.288,38169857,748.919,47.636,14.2915,9.036,3.4465,1.577,25.251,132.322,0.000,64.4255,0.000,0.000,0.000,0.000,0.000,0.000,-1.441,0.000,0.000,0.000,0.000,0.000
1,NaN,NaN,1901,0.9850,0.016,6.354,0.000,78.1350,2.8260,6.662,29.305,5.182,38.438,34.614,0.063,0.001,0.911,3.973,616.801,39.9025,11.759,7.082,5.761,53.224,204.1965,278.689,1.669,43.170,169.74,9.40,44.695,94.80,33.619,7.696,0.0,14.832,NaN,1.1095,9.0905,0.00,0.00,110.585,99.18,0.811,3955.7195,6.542,96.5535,31.633,720.1495,3803.6835,433.140,85.7115,5.108958e+10,26.9395,3.856,24.3235,7.178,222.1435,157.4445,1173.3235,0.000,0.000,8.7945,4.872,2.310,0.466,21.378,40.6525,111.831,14.2915,9.0905,47.636,9.036,3.4465,1.577,25.251,132.322,0.000,0.00,0.0,NaN,0.0,0.0,0.0,0.0,0.0,13.4785,5.189,59.3455,14.619,444.7815,73.132,2344.101,6.443,166.664,NaN,5.999,5.458,0.476,0.000,3.0825,NaN,4.570,16.664,505.288,38658803,748.919,47.636,14.2915,9.036,3.4465,1.577,25.251,132.322,0.000,64.4255,0.000,0.000,0.000,0.000,0.000,0.000,-1.441,0.000,0.000,0.000,0.000,0.000
2,NaN,NaN,1902,-6.3410,-0.106,6.354,0.000,-39.3500,-2.5350,6.662,29.305,5.182,38.438,34.614,0.063,0.001,0.911,3.973,616.801,39.9025,11.759,7.082,5.761,53.224,204.1965,278.689,1.563,39.922,169.74,9.40,44.695,94.80,33.619,7.696,0.0,14.832,NaN,1.1095,9.0905,0.00,0.00,110.585,99.18,0.811,3955.7195,6.542,96.5535,31.633,720.1495,3803.6835,433.140,85.7115,5.006722e+10,26.9395,3.856,24.3235,7.178,222.1435,157.4445,1173.3235,0.000,0.000,8.7945,4.872,2.310,0.466,21.378,40.6525,111.831,14.2915,9.0905,47.636,9.036,3.4465,1.577,25.251,132.322,0.000,0.00,0.0,NaN,0.0,0.0,0.0,0.0,0.0,13.4785,5.189,59.3455,14.619,444.7815,73.132,2344.101,3.908,99.805,NaN,5.999,5.458,0.476,0.000,3.0825,NaN,4.570,16.664,505.288,39153251,748.919,47.636,14.2915,9.036,3.4465,1.577,25.251,132.322,0.000,64.4255,0.000,0.000,0.000,0.000,0.000,0.000,-1.441,0.000,0.000,0.000,0.000,0.000
3,NaN,NaN,1903,9.8960,0.155,6.354,0.000,136.9050,5.3500,6.662,29.305,5.182,38.438,34.614,0.063,0.001,0.911,3.973,616.801,39.9025,11.759,7.082,5.761,53.224,204.1965,278.689,1.718,43.339,169.74,9.40,44.695,94.80,33.619,7.696,0.0,14.832,NaN,1.1095,9.0905,0.00,0.00,110.585,99.18,0.811,3955.7195,6.542,96.5535,31.633,720.1495,3803.6835,433.140,85.7115,5.283652e+10,26.9395,3.856,24.3235,7.178,222.1435,157.4445,1173.3235,0.000,0.000,8.7945,4.872,2.310,0.466,21.378,40.6525,111.831,14.2915,9.0905,47.636,9.036,3.4465,1.577,25.251,132.322,0.000,0.00,0.0,NaN,0.0,0.0,0.0,0.0,0.0,13.4785,5.189,59.3455,14.619,444.7815,73.132,2344.101,9.257,233.565,NaN,5.999,5.458,0.476,0.000,3.0825,NaN,4.570,16.664,505.288,39635616,748.919,47.636,14.2915,9.036,3.4465,1.577,25.251,132.322,0.000,64.4255,0.000,0.000,0.000,0.000,0.000,0.000,-1.441,0.000,0.000,0.000,0.000,0.000
4,NaN,NaN,1904,9.4790,0.163,6.354,0.000,12.8140,1.1860,6.662,29.305,5.182,38.438,34.614,0.063,0.001,0.911,3.973,616.801,39.9025,11.759,7.082,5.761,53.224,204.1965,278.689,1.881,46.891,169.74,9.40,44.695,94.80,33.619,7.696,0.0,14.832,NaN,1.1095,9.0905,0.00,0.00,110.585,99.18,0.811,3955.7195,6.542,96.5535,31.633,720.1495,3803.6835,433.140,85.7115,5.354404e+10,26.9395,3.856,24.3235,7.178,222.1435,157.4445,1173.3235,0.000,0.000,8.7945,4.872,2.310,0.466,21.378,40.6525,111.831,14.2915,9.0905,47.636,9.036,3.4465,1.577,25.251,132.322,0.000,0.00,0.0,NaN,0.0,0.0,0.0,0.0,0.0,13.4785,5.189,59.3455,14.619,444.7815,73.132,2344.101,10.444,260.407,NaN,5.999,5.458,0.476,0.000,3.0825,NaN,4.570,16.664,505.288,40105530,748.919,47.636,14.2915,9.036,3.4465,1.577,25.251,132.322,0.000,64.4255,0.000,0.000,0.000,0.000,0.000,0.000,-1.441,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,NaN,NaN,2016,-1.1630,-36.789,-1.421,-10.822,5.3880,25.4300,1.144,22.548,4.422,41.865,204.804,1.421,19.030,28.321,108.279,641.360,54.6700,4.303,31.135,25.597,620.408,517.5940,2371.987,3126.366,11952.934,248.32,10.95,135.380,217.97,61.790,18.680,0.0,20.800,NaN,10.9510,29.6550,0.02,0.01,247.630,158.82,0.716,7618.3350,-0.539,94.8360,-10.249,1889.7290,7224.9400,833.358,88.0220,2.783160e+12,24.9530,-2.458,22.3980,-11.248,446.3080,236.2400,1706.3550,750.800,2870.508,7.5440,35.121,2.357,12.208,46.969,71.4190,179.573,11.9750,29.6550,113.378,46.785,5.1640,32.797,102.896,393.401,0.278,0.69,0.0,NaN,0.0,0.0,0.0,0.0,0.0,8.4000,-2.902,41.3030,-24.598,823.0120,79.524,3146.599,497.372,1901.585,NaN,41.868,5.818,1.382,1.514,27.5390,NaN,4.422,105.291,946.756,261556384,1992.624,113.378,11.9750,46.785,5.1640,32.797,102.896,393.401,0.008,296.9500,0.003,0.040,0.053,0.076,0.203,0.004,52.819,0.001,0.005,0.014,0.038,0.055
117,NaN,NaN,2017,1.1070,34.611,-3.163,-23.750,-4.2040,-20.9100,4.167,83.026,5.134,49.348,-14.073,1.172,-3.986,24.335,91.953,650.024,58.1700,7.156,32.029,44.398,664.806,559.0760,2512.012,3160.977,11943.946,255.48,13.06,147.960,222.64,55.830,18.630,0.0,18.850,NaN,13.0590,31.7200,0.03,0.00,254.360,165.34,0.710,7842.9710,4.354,95.0070,82.285,1972.0150,7451.3790,841.259,87.5290,2.924270e+12,21.9490,-3.171,20.8200,-14.154,432.1530,210.9570,1632.9190,727.050,2747.203,7.3240,-0.825,2.244,-0.388,46.581,70.3950,176.009,12.4710,31.7200,119.858,0.719,4.9930,0.740,103.637,391.598,0.438,1.12,0.0,NaN,0.0,0.0,0.0,0.0,0.0,7.4110,6.323,42.1580,52.042,875.0540,71.226,3306.448,476.461,1800.339,NaN,49.344,18.549,1.573,5.108,32.6480,NaN,5.134,123.361,961.115,264650976,2075.650,119.858,12.4710,0.719,4.9930,0.740,103.637,391.598,0.012,36.9330,0.003,0.020,0.073,0.113,0.274,0.000,-100.000,0.000,-0.014,0.000,0.000,0.000
118,NaN,NaN,2018,20.9270,661.493,0.133,0.967,-3.5260,-16.7980,7.990,165.835,5.371,53.536,44.016,1.564,10.711,35.047,130.933,658.333,59.9780,18.602,35.177,123.671,788.476,597.7870,2945.699,3822.470,14280.503,268.28,14.33,160.010,235.41,57.450,16.830,0.0,17.950,NaN,14.3300,31.3650,0.02,0.19,266.780,175.63,0.729,8374.0440,7.935,94.9590,156.470,2128.4850,7951.8840,879.477,88.2410,3.075460e+12,21.5350,3.039,19.8660,13.132,445.2860,214.6300,1663.5610,728.017,2719.824,6.3090,-10.216,1.866,-4.759,41.822,62.8760,156.246,11.7570,31.3650,117.179,9.036,5.0410,9.365,113.002,422.168,0.559,1.50,0.0,NaN,0.0,0.0,0.0,0.0,0.0,6.7280,2.248,39.9160,19.667,894.7210,67.060,3342.624,459.664,1717.274,NaN,53.536,9.091,1.589,2.968,35.6160,NaN,5.371,133.057,996.673,267670560,2241.485,117.179,11.7570,9.036,5.0410,9.365,113.002,422.168,0.007,-31.5900,0.002,-0.023,0.050,0.075,0.186,0.071,-1.441,0.021,0.467,0.467,0.710,1.745
119,NaN,NaN,2019,10.4680,400.129,-7.168,-52.182,-3.4030,-15.6440,7.238,162.229,5.147,53.025,69.163,2.466,24.239,59.286,219.071,662.578,62.5820,20.280,39.455,159.903,948.379,644.7650,3504.399,4222.599,15603.106,280.50,14.35,174.490,247.39,62.320,16.550,0.0,10.580,NaN,14.3460,31.4280,0.05,0.48,278.820,184.74,0.811,8882.0660,6.489,94.2960,138.122,2266.6070,8375.4370,914.141,88.7270,1.632345e+11,22.3510,-1.366,18.2720,-6.083,439.2030,230.2810,1622.9180,675.834,2497.304,5.9360,-2.035,1.705,-0.851,40.972,61.1550,151.396,11.2720,31.4280,116.131,21.333,5.7040,24.107,137.109,506.637,0.599,1.68,0.0,NaN,0.0,0.0,0.0,0.0,0.0,3.7950,-1.754,36.5690,-15.698,879.0240,39.095,3248.120,444.020,1640.715,NaN,53.011,-0.258,1.478,-0.092,35.5240,NaN,5.145,131.266,1030.280,270625568,2403.714,116.131,11.2720,21.333,5.7040,24.107,137.109,506.637,0.018,169.1390,0.006,0.084,0.134,0.185,0.494,0.172,155.465,0.050,0.726,1.194,1.774,4.410
120,NaN,NaN,2020,-8.7040,-367.529,-6.556,-44.310,-4.6660,-20.7200,-11.782,-283.195,5.780,58.057,2.796,2.874,1.658,60.944,222.811,663.488,65.8280,-4.638,42.650,-43.986,904.393,661.2590,3306.455,3855.071,14094.106,276.31,15.88,180.870,238.91,51.280,19.450,0.0,6.760,NaN,15.8820,36.2820,0.05,0.47,274.760,182.30,0.811,7752.6000,-13.083,92.9050,-296.543,1970.0650,7202.5400,873.453,86.9520,1.632345e+11,18.6640,-5.446,19.5840,-23.920,415.2830,187.4790,1518.2730,631.525,2308.849,7.0790,17.146,2.263,7.025,47.996,71.1090,175.474,13.2050,36.2820,132.647,9.735,7.0950,13.347,150.456,550.067,0.561,1.55,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2.4600,-26.010,30.6710,-228.637,650.3870,24.715,2377.812,423.299,1547.579,NaN,58.065,10.302,1.848,3.660,39.1830,NaN,5.780,143.254,1004.520,273523616,2120.519,132.647,13.2050,9.735,7.0950,13.347,150.456,550.067,0.018,772.1360,0.055,1.032,1.166,0.183,4.264,0.171,-2.292,0.055,-0.027,1.166,1.718,4.264

In [ ]:
def detect_outliers_iqr(column):
    Q1 = column.quantile(0.25)
    Q3 = column.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return (column < lower_bound) | (column > upper_bound)

In [ ]:
outliers = df.apply(detect_outliers_iqr)

In [ ]:
outliers_count = outliers.sum()

In [ ]:
print("Number of outliers in each column:")
print(outliers_count)

Number of outliers in each column:
iso_code                   0
country                    0
year                       0
coal_prod_change_pct      11
coal_prod_change_twh      31
                          ..
wind_share_energy          8
wind_cons_change_twh      10
wind_consumption          10
wind_elec_per_capita       4
wind_energy_per_capita    11
Length: 128, dtype: int64

In [ ]:
from scipy.stats.mstats import winsorize